---
bibliography: riskassess.bib
csl: plos.csl
fontsize: 10pt
geometry: left=2cm, right=2cm, top=2cm, bottom=3cm, footskip = .5cm
link-citations: yes
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document:
    includes:
      in_header: latex/header.tex
    keep_tex: yes
subparagraph: yes
urlcolor: blue
---

```{r setup, include=FALSE}

# library(tint)
# # invalidate cache when the package version changes
# knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tint'))
# options(htmltools.dir.version = FALSE)

#Default Rmd options
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      dev = "cairo_pdf",
                      warning = FALSE,
                      fig.width = 4,
                      fig.asp = 0.45,
                      fig.align = 'center'
                      ) #allows for inserting R code into captions

#Plotting and data libraries
#remotes::install_github("noaa-edab/ecodata@0.1.0") #change to 2020 ecodata version for release
library(tidyverse)
library(tidyr)
library(ecodata)
library(here)
library(kableExtra)
library(flextable)

```

# 2022 EAFM Risk Tables

Tables in word for NOAA Tech Memo Rankin et al 2023

```{r sptable,  echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}

#tab.cap="Species level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)\\label{sptable}",

# spplist     oc,  sc,  flk, scp, bsb, mack, but, lsq, ssq, gtile,  btile,  blu, dog, monk
risk.species<-data.frame(
  Species = c("Ocean Quahog", "Surfclam", "Summer flounder", "Scup", "Black sea bass", "Atl. mackerel", "Chub mackerel", "Butterfish", "Longfin squid", "Shortfin squid", "Golden tilefish", "Blueline tilefish", "Bluefish", "Spiny dogfish", "Monkfish", "Unmanaged forage", "Deepsea corals"),
  Assess  = c("l", "l", "l",  "l", "l", "l", "h", "l", "lm", "lm", "l", "h", "l", "lm", "h", "na", "na"),
  Fstatus = c("l", "l", "l", "l", "l", "h", "lm", "l", "lm", "lm", "l", "h", "l", "l", "lm", "na", "na"),
  Bstatus = c("l", "l", "lm", "l", "l", "h", "lm", "lm", "lm", "lm", "lm", "mh", "h", "lm", "lm", "na", "na"),
  FW1Pred = c("l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l"),
  FW1Prey = c("l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "lm", "l"),
  FW2Prey = c("l", "l", "l", "l", "l", "l", "l", "l", "lm", "lm", "l", "l", "l", "l", "l", "lm", "l"),
  Climate = c("h", "mh", "lm", "lm", "mh", "lm", "na", "l", "l", "l", "mh", "mh","l", "l", "l", "na", "na"),
  DistShift = c("mh", "mh", "mh", "mh", "mh", "mh", "na", "h", "mh", "h", "l", "l", "mh", "h", "mh", "na", "na"),
  EstHabitat = c("l", "l", "h", "h", "h", "l", "l", "l", "l", "l", "l", "l", "h", "l", "l", "na", "na")#,
#  OffHabitat = c("na", "na", "l", "l", "l", "l", "na", "l", "l", "h", "na", "na", "na", "l", "l", "na", "na")#,
)

# these elements were removed by the council
#  PopDiv = c("na", "na", "na", "na", "na", "na", "na", "na", "na", "na", "na", "na", "na", "na"),
#  FoodSafe = c(),

# one column test
# risk.species %>%
#   mutate(Fstatus = 
#     cell_spec(Fstatus, format="latex", color = "black", align = "c", background =factor(Fstatus, c("na", "l", "lm", "mh", "h"),c("white", "green", "yellow", "orange", "red")))) %>%
#   kable(risk.species, format="latex", escape = F, booktabs = T, linesep = "")

#generalize to all
# risk.species %>%
#   mutate_at(vars(-Species), function(x){ 
#     cell_spec(x, format="latex", color = "gray", align = "c", background =factor(x, c("na", "l", "lm", "mh", "h"),c("white", "green", "yellow", "orange", "red")))}) %>%
#   kable(risk.species, format="latex", escape = F, booktabs = T, linesep = "", 
#         caption="Species level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)\\label{sptable}") %>%
#   kable_styling(latex_options = "scale_down") #%>%
# #kable_as_image()

colourer <- scales::col_factor(
    palette = c("white", "green", "yellow", "orange", "red"),
    domain = c("na", "l", "lm", "mh", "h"),
    ordered = TRUE
  )

set_flextable_defaults(padding = 0, font.size = 9)

risk.species %>%
  flextable::flextable() %>%
  flextable::color(color = "gray", part = "body") %>% 
  flextable::align(align = "center", part = "all") %>%
  flextable::bg(j = c(
      "Assess", "Fstatus", "Bstatus", "FW1Pred", "FW1Prey", "FW2Prey",
      "Climate", "DistShift", "EstHabitat"
    ),
    bg = colourer, part = "body") %>%
  flextable::color(color = "black", j="Species") %>%
  flextable::set_caption("Species level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)") %>%
  flextable::autofit()
  #flextable::set_table_properties(width = 1, layout = "autofit")


```

\newpage

```{r ecotable,  echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
  
#tab.cap="Ecosystem level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)\\label{sptable}",

risk.eco<-data.frame(
  System = c("Mid-Atlantic"),
  EcoProd = c("lm"),
  #EcoDiv = c("lm"),
  CommRev = c("mh"),
  RecVal = c("lm"),
  FishRes1 = c("l"),
  FishRes4 = c("mh"),
  #CommJobs = c("mh"),
  #RecJobs = c("l"),
  FleetDiv = c("l"),
  Social = c("lm"),
  ComFood = c("h"),
  RecFood = c("mh")
)

#make table
# risk.eco %>%
#   mutate_at(vars(-System), function(x){ 
#     cell_spec(x, format="latex", color = "gray", align = "c", background =factor(x, c("na", "l", "lm", "mh", "h"),c("white", "green", "yellow", "orange", "red")))}) %>%
#   kable(risk.eco, format="latex", escape = F, booktabs = T, linesep = "",
#         caption="Ecosystem level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)\\label{ecotable}") %>%
#   kable_styling(latex_options = "scale_down") #%>%
#   #kable_as_image()

risk.eco %>%
  flextable::flextable() %>%
  flextable::color(color = "gray", part = "body") %>% 
  flextable::align(align = "center", part = "all") %>%
  flextable::bg(j = c(
      "EcoProd", "CommRev", "RecVal", "FishRes1", "FishRes4",
      "FleetDiv", "Social", "ComFood", "RecFood"
    ),
    bg = colourer, part = "body") %>%
  flextable::color(color = "black", j="System") %>%
  flextable::set_caption("Ecosystem level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)") %>%
  flextable::autofit()
  #flextable::set_table_properties(width = 1, layout = "autofit")

```

\newpage

```{r spsectable,  echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
#tab.cap="Species and sector level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)\\label{sptable}",

risk.sppsector<-data.frame(
  Species = c("Ocean Quahog-C", "Surfclam-C", "Summer flounder-R", "Summer flounder-C","Scup-R", "Scup-C","Black sea bass-R", "Black sea bass-C","Atl. mackerel-R", "Atl. mackerel-C","Butterfish-C", "Longfin squid-C", "Shortfin squid-C", "Golden tilefish-R", "Golden tilefish-C","Blueline tilefish-R","Blueline tilefish-C", "Bluefish-R", "Bluefish-C","Spiny dogfish-R", "Spiny dogfish-C", "Chub mackerel-C", "Unmanaged forage", "Deepsea corals"),
  MgtControl =  c(1,1,3,2,2,1,4,4,2,1,1,1,2,9,1,2,2,2,1,1,1,1,1,9),
  TecInteract = c(1,1,1,3,1,2,1,2,1,2,2,3,2,1,1,1,1,1,1,1,3,2,1,9),
  OceanUse =    c(2,2,2,2,2,3,3,4,1,3,3,4,2,1,1,1,1,1,2,1,3,2,3,3),
  RegComplex =  c(1,1,3,3,3,3,3,3,2,4,3,3,3,1,1,2,2,2,2,1,3,2,1,9),
  Discards =    c(3,3,4,3,3,3,4,4,1,2,3,4,1,1,1,1,1,3,2,1,2,1,1,9),
  Allocation =  c(1,1,4,1,4,1,4,1,1,4,1,1,4,1,1,1,1,4,1,1,1,1,1,9) 
)

#convert to text for consistency
risk.sppsector <- risk.sppsector %>%
     mutate_at(vars(-Species), function(x){
       recode(x,'1'="l",'2'="lm",'3'="mh",'4'="h",'9'="na")}) %>%
     as.data.frame()

#make table
# risk.sppsector %>%
#   mutate_at(vars(-Species), function(x){ 
#     cell_spec(x, format="latex", color = "gray", align = "c", background =factor(x, c("na", "l", "lm", "mh", "h"),c("white", "green", "yellow", "orange", "red")))}) %>%
#   kable(risk.sppsector, format="latex", escape = F, booktabs = T, linesep = "",
#         caption="Species and sector level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)\\label{spsectable}") %>%
#   kable_styling(font_size =  9) #%>%
#   #kable_as_image()

risk.sppsector %>%
  flextable::flextable() %>%
  flextable::color(color = "gray", part = "body") %>% 
  flextable::align(align = "center", part = "all") %>%
  flextable::bg(j = c(
      "MgtControl", "TecInteract", "OceanUse", 
      "RegComplex", "Discards", "Allocation"
    ),
    bg = colourer, part = "body") %>%
  flextable::color(color = "black", j="Species") %>%
  flextable::set_caption("Species and sector level risk analysis results; l=low risk (green), lm= low-moderate risk (yellow), mh=moderate to high risk (orange), h=high risk (red)") %>%
  flextable::autofit()
  #flextable::set_table_properties(width = 1, layout = "autofit")

```


