## Developing Offshore Habitat Risk Indicators for the    
## Mid Atlantic Risk Assessment. Indicators were informed 
## by the ESP                                             
##
## Author: M.T.Grezlik                                    
## Date: 01/30/2025  

# ESP for Bluefish had indicators of Distribution (6), Climate (7),
# and Natural Mortality (7). Distribution indicators were generated by a VAST
# model of the NEUS. Reception to indiviual indicators was mixed and is
# described in the ESP.

# Distribution indicators -------------------------------------------

## Center of Gravity -------------------------------------------

# ### setup data --------------------------------------------------------
# load(here::here('offshore_habitat/data-raw/center_of_gravity.rda'))
# 
# center_of_gravity <- center_of_gravity |>
#   dplyr::mutate(EPU = 'MAB') |> 
#   dplyr::mutate(Units = 'km') |> 
#   dplyr::rename(Time = YEAR) |> 
#   dplyr::rename(Value = DATA_VALUE) |>
#   dplyr::rename(Var = INDICATOR_NAME) |> 
#   dplyr::select(Time, Value, Var, EPU, Units)
# 
# ### save data as .rda file -------------------------------------------
# save(center_of_gravity, file = here::here('offshore_habitat/data/bf_cog.rda'))


### plot using function ---------------------------------------
source(here::here('offshore_habitat/R/plot_bf_cog.R'))
plot_bf_cog()

# Climate indicators -------------------------------------------

## 18 degree days -------------------------------------------

### load data --------------------------------------------------------
# # first and last 18 day
# load(here::here('offshore_habitat/data-raw/first_18_day.rda'))
# 
# first_18_day <- first_18_day |>
#   dplyr::mutate(EPU = 'MAB') |> 
#   dplyr::mutate(Units = 'doy') |> 
#   dplyr::rename(Time = YEAR) |> 
#   dplyr::rename(Value = DATA_VALUE) |>
#   dplyr::rename(Var = INDICATOR_NAME) |> 
#   dplyr::select(Time, Value, Var, EPU, Units)
# 
# load(here::here('offshore_habitat/data-raw/last_18_day.rda'))
# 
# last_18_day <- last_18_day |>
#   dplyr::mutate(EPU = 'MAB') |> 
#   dplyr::mutate(Units = 'doy') |> 
#   dplyr::rename(Time = YEAR) |> 
#   dplyr::rename(Value = DATA_VALUE) |>
#   dplyr::rename(Var = INDICATOR_NAME) |> 
#   dplyr::select(Time, Value, Var, EPU, Units)
# 
# # n days
# load(here::here('offshore_habitat/data-raw/n_18_day.rda'))
# 
# n_18_day <- n_18_day |>
#   dplyr::mutate(EPU = 'MAB') |> 
#   dplyr::mutate(Units = 'number of days') |> 
#   dplyr::rename(Time = YEAR) |> 
#   dplyr::rename(Value = DATA_VALUE) |>
#   dplyr::rename(Var = INDICATOR_NAME) |> 
#   dplyr::select(Time, Value, Var, EPU, Units)
# 
### save data as .rda files -------------------------------------------
# save(first_18_day, file = here::here('offshore_habitat/data/first_18_day.rda'))
# save(last_18_day, file = here::here('offshore_habitat/data/last_18_day.rda'))
# save(n_18_day, file = here::here('offshore_habitat/data/n_18_day.rda'))



### plot using function ---------------------------------------
source(here::here('offshore_habitat/R/plot_bf_climate.R'))
plot_bf_climate()


## July proportions -------------------------------------------

### load data --------------------------------------------------------
# load(here::here('offshore_habitat/data-raw/july_proportion.rda'))
# 
# # put in ecodata format
# july_proportion <- july_proportion |>
#   dplyr::mutate(EPU = 'MAB') |> 
#   dplyr::mutate(Units = 'proportion') |> 
#   dplyr::rename(Time = YEAR) |> 
#   dplyr::rename(Value = DATA_VALUE) |>
#   dplyr::rename(Var = INDICATOR_NAME) |> 
#   dplyr::select(Time, Value, Var, EPU, Units)
 
### save as rda file -------------------------------------------
# save(july_proportion, file = here::here('offshore_habitat/data/july_proportion.rda'))


### plot using function ---------------------------------------
source(here::here('offshore_habitat/R/plot_bf_july_proportion.R'))
plot_bf_july_proportion()


# Wind indicators -------------------------------------------

## mean April and May winds -------------------------------------------
### load data --------------------------------------------------------
# load(here::here('offshore_habitat/data-raw/wind_indicators.rda'))
# 
# # put in ecodata format
# wind_indicators <- wind_indicators |>
#   dplyr::mutate(EPU = 'MAB') |> 
#   dplyr::mutate(Units = 'unspecified') |> 
#   dplyr::rename(Time = YEAR) |> 
#   dplyr::rename(Value = DATA_VALUE) |>
#   dplyr::rename(Var = INDICATOR_NAME) |> 
#   dplyr::select(Time, Value, Var, EPU, Units)
# 

### save as rda file -------------------------------------------
# save(wind_indicators, file = here::here('offshore_habitat/data/wind_indicators.rda'))

# plot using function
source(here::here('offshore_habitat/R/plot_bf_wind_indicators.R'))
plot_bf_wind_indicators()


### plot using function ---------------------------------------
source(here::here('offshore_habitat/R/plot_bf_wind_indicators.R'))
plot_bf_wind_indicators()

# Natural Mortality indicators -------------------------------------------

## Mako Shark B/Bmsy -------------------------------------------

### load data --------------------------------------------------------
# load(here::here('offshore_habitat/data-raw/mako.rda'))

# put in ecodata format
# mako <- mako |>
#   dplyr::mutate(EPU = 'MAB') |> 
#   dplyr::mutate(Units = 'B/Bmsy') |> 
#   dplyr::rename(Time = YEAR) |> 
#   dplyr::rename(Value = DATA_VALUE) |>
#   dplyr::rename(Var = INDICATOR_NAME) |> 
#   dplyr::select(Time, Value, Var, EPU, Units)

### save as rda file -------------------------------------------
# save(mako, file = here::here('offshore_habitat/data/mako.rda'))

### plot using function ---------------------------------------
source(here::here('offshore_habitat/R/plot_bf_mako.R'))
plot_bf_mako()

## BF condition -------------------------------------------

### load data --------------------------------------------------------
# load(here::here('offshore_habitat/data-raw/relative_condition.rda'))
# 
# # put in ecodata format
# relative_condition <- relative_condition |>
#   dplyr::mutate(EPU = 'MAB') |> 
#   dplyr::mutate(Units = 'relative condition') |> 
#   dplyr::rename(Time = YEAR) |> 
#   dplyr::rename(Value = DATA_VALUE) |>
#   dplyr::rename(Var = INDICATOR_NAME) |> 
#   dplyr::select(Time, Value, Var, EPU, Units)

### save as rda file -------------------------------------------
# save(relative_condition, file = here::here('offshore_habitat/data/bf_condition.rda'))

### plot using function ---------------------------------------
source(here::here('offshore_habitat/R/plot_bf_condition.R'))
plot_bf_condition()
